repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=250']
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-case-conflict


  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.7.1
    hooks:
      - id: reorder-python-imports
        args: [--py3-plus]

  # - repo: https://github.com/jazzband/pip-tools
  #   rev: 6.5.1
  #   hooks:
  #    - id: pip-compile
